// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Customer is the predicate function for customer builders.
type Customer func(*sql.Selector)

// Gender is the predicate function for gender builders.
type Gender func(*sql.Selector)

// Personal is the predicate function for personal builders.
type Personal func(*sql.Selector)

// Title is the predicate function for title builders.
type Title func(*sql.Selector)
