// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/jirayuSai/app/ent/customer"
	"github.com/jirayuSai/app/ent/personal"
)

// PersonalCreate is the builder for creating a Personal entity.
type PersonalCreate struct {
	config
	mutation *PersonalMutation
	hooks    []Hook
}

// SetName sets the Name field.
func (pc *PersonalCreate) SetName(s string) *PersonalCreate {
	pc.mutation.SetName(s)
	return pc
}

// SetEmail sets the Email field.
func (pc *PersonalCreate) SetEmail(s string) *PersonalCreate {
	pc.mutation.SetEmail(s)
	return pc
}

// SetPassword sets the Password field.
func (pc *PersonalCreate) SetPassword(s string) *PersonalCreate {
	pc.mutation.SetPassword(s)
	return pc
}

// AddCustomerIDs adds the customers edge to Customer by ids.
func (pc *PersonalCreate) AddCustomerIDs(ids ...int) *PersonalCreate {
	pc.mutation.AddCustomerIDs(ids...)
	return pc
}

// AddCustomers adds the customers edges to Customer.
func (pc *PersonalCreate) AddCustomers(c ...*Customer) *PersonalCreate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return pc.AddCustomerIDs(ids...)
}

// Mutation returns the PersonalMutation object of the builder.
func (pc *PersonalCreate) Mutation() *PersonalMutation {
	return pc.mutation
}

// Save creates the Personal in the database.
func (pc *PersonalCreate) Save(ctx context.Context) (*Personal, error) {
	if _, ok := pc.mutation.Name(); !ok {
		return nil, &ValidationError{Name: "Name", err: errors.New("ent: missing required field \"Name\"")}
	}
	if _, ok := pc.mutation.Email(); !ok {
		return nil, &ValidationError{Name: "Email", err: errors.New("ent: missing required field \"Email\"")}
	}
	if _, ok := pc.mutation.Password(); !ok {
		return nil, &ValidationError{Name: "Password", err: errors.New("ent: missing required field \"Password\"")}
	}
	var (
		err  error
		node *Personal
	)
	if len(pc.hooks) == 0 {
		node, err = pc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PersonalMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pc.mutation = mutation
			node, err = pc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(pc.hooks) - 1; i >= 0; i-- {
			mut = pc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (pc *PersonalCreate) SaveX(ctx context.Context) *Personal {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (pc *PersonalCreate) sqlSave(ctx context.Context) (*Personal, error) {
	pe, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	pe.ID = int(id)
	return pe, nil
}

func (pc *PersonalCreate) createSpec() (*Personal, *sqlgraph.CreateSpec) {
	var (
		pe    = &Personal{config: pc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: personal.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: personal.FieldID,
			},
		}
	)
	if value, ok := pc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: personal.FieldName,
		})
		pe.Name = value
	}
	if value, ok := pc.mutation.Email(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: personal.FieldEmail,
		})
		pe.Email = value
	}
	if value, ok := pc.mutation.Password(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: personal.FieldPassword,
		})
		pe.Password = value
	}
	if nodes := pc.mutation.CustomersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   personal.CustomersTable,
			Columns: []string{personal.CustomersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: customer.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return pe, _spec
}
