// Code generated by entc, DO NOT EDIT.

package title

const (
	// Label holds the string label denoting the title type in the database.
	Label = "title"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitleName holds the string denoting the titlename field in the database.
	FieldTitleName = "title_name"

	// EdgeCustomers holds the string denoting the customers edge name in mutations.
	EdgeCustomers = "customers"

	// Table holds the table name of the title in the database.
	Table = "titles"
	// CustomersTable is the table the holds the customers relation/edge.
	CustomersTable = "customers"
	// CustomersInverseTable is the table name for the Customer entity.
	// It exists in this package in order to avoid circular dependency with the "customer" package.
	CustomersInverseTable = "customers"
	// CustomersColumn is the table column denoting the customers relation/edge.
	CustomersColumn = "Title_ID"
)

// Columns holds all SQL columns for title fields.
var Columns = []string{
	FieldID,
	FieldTitleName,
}
