// Code generated by entc, DO NOT EDIT.

package title

import (
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/jirayuSai/app/ent/predicate"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Title {
	return predicate.Title(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Title {
	return predicate.Title(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Title {
	return predicate.Title(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Title {
	return predicate.Title(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Title {
	return predicate.Title(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Title {
	return predicate.Title(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Title {
	return predicate.Title(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Title {
	return predicate.Title(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Title {
	return predicate.Title(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// TitleName applies equality check predicate on the "TitleName" field. It's identical to TitleNameEQ.
func TitleName(v string) predicate.Title {
	return predicate.Title(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTitleName), v))
	})
}

// TitleNameEQ applies the EQ predicate on the "TitleName" field.
func TitleNameEQ(v string) predicate.Title {
	return predicate.Title(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTitleName), v))
	})
}

// TitleNameNEQ applies the NEQ predicate on the "TitleName" field.
func TitleNameNEQ(v string) predicate.Title {
	return predicate.Title(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldTitleName), v))
	})
}

// TitleNameIn applies the In predicate on the "TitleName" field.
func TitleNameIn(vs ...string) predicate.Title {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Title(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldTitleName), v...))
	})
}

// TitleNameNotIn applies the NotIn predicate on the "TitleName" field.
func TitleNameNotIn(vs ...string) predicate.Title {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Title(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldTitleName), v...))
	})
}

// TitleNameGT applies the GT predicate on the "TitleName" field.
func TitleNameGT(v string) predicate.Title {
	return predicate.Title(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldTitleName), v))
	})
}

// TitleNameGTE applies the GTE predicate on the "TitleName" field.
func TitleNameGTE(v string) predicate.Title {
	return predicate.Title(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldTitleName), v))
	})
}

// TitleNameLT applies the LT predicate on the "TitleName" field.
func TitleNameLT(v string) predicate.Title {
	return predicate.Title(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldTitleName), v))
	})
}

// TitleNameLTE applies the LTE predicate on the "TitleName" field.
func TitleNameLTE(v string) predicate.Title {
	return predicate.Title(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldTitleName), v))
	})
}

// TitleNameContains applies the Contains predicate on the "TitleName" field.
func TitleNameContains(v string) predicate.Title {
	return predicate.Title(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldTitleName), v))
	})
}

// TitleNameHasPrefix applies the HasPrefix predicate on the "TitleName" field.
func TitleNameHasPrefix(v string) predicate.Title {
	return predicate.Title(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldTitleName), v))
	})
}

// TitleNameHasSuffix applies the HasSuffix predicate on the "TitleName" field.
func TitleNameHasSuffix(v string) predicate.Title {
	return predicate.Title(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldTitleName), v))
	})
}

// TitleNameEqualFold applies the EqualFold predicate on the "TitleName" field.
func TitleNameEqualFold(v string) predicate.Title {
	return predicate.Title(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldTitleName), v))
	})
}

// TitleNameContainsFold applies the ContainsFold predicate on the "TitleName" field.
func TitleNameContainsFold(v string) predicate.Title {
	return predicate.Title(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldTitleName), v))
	})
}

// HasCustomers applies the HasEdge predicate on the "customers" edge.
func HasCustomers() predicate.Title {
	return predicate.Title(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(CustomersTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CustomersTable, CustomersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCustomersWith applies the HasEdge predicate on the "customers" edge with a given conditions (other predicates).
func HasCustomersWith(preds ...predicate.Customer) predicate.Title {
	return predicate.Title(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(CustomersInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CustomersTable, CustomersColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Title) predicate.Title {
	return predicate.Title(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Title) predicate.Title {
	return predicate.Title(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Title) predicate.Title {
	return predicate.Title(func(s *sql.Selector) {
		p(s.Not())
	})
}
